import { icons } from "assets";
import {
  CreateNonRecurringClientSchema,
  createNonRecurringTaskDefaultValues,
} from "validations/createTask";
import schemas from "./formFieldSchemas";
import { FormBuilderFieldTypes } from "./renderFieldsComponent";
import { v4 as uuidv4 } from "uuid";

const availableFields = [
  {
    id: uuidv4(),
    icon: icons.singleLine,
    label: "Single Line",
    fieldType: FormBuilderFieldTypes.SINGLE_LINE,
    defaultValues: schemas.singleLineDefaultValues,
    schema: schemas.singleLineSchema,
  },
  {
    id: uuidv4(),
    icon: icons.multiLine,
    label: "Multi Line",
    fieldType: FormBuilderFieldTypes.MULTI_LINE,
    defaultValues: schemas.multiLineDefaultValues,
    schema: schemas.multiLineSchema,
  },
  {
    id: uuidv4(),
    icon: icons.numbers,
    label: "Number",
    fieldType: FormBuilderFieldTypes.NUMBER,
    defaultValues: schemas.numberDefaultValues,
    schema: schemas.numberSchema,
  },
  {
    id: uuidv4(),
    icon: icons.name,
    label: "Name",
    fieldType: FormBuilderFieldTypes.NAME,
    defaultValues: schemas.nameDefaultValues,
    schema: schemas.nameSchema,
  },
  {
    id: uuidv4(),
    icon: icons.address,
    label: "Address",
    fieldType: FormBuilderFieldTypes.ADDRESS,
    defaultValues: schemas.addressDefaultValues,
    schema: schemas.addressSchema,
  },
  {
    id: uuidv4(),
    icon: icons.mobileNumber,
    label: "Mobile Number",
    fieldType: FormBuilderFieldTypes.PHONE,
    defaultValues: schemas.mobileNumberDefaultValues,
    schema: schemas.mobileNumberSchema,
  },
  {
    id: uuidv4(),
    icon: icons.email,
    label: "Email",
    fieldType: FormBuilderFieldTypes.EMAIL,
    defaultValues: schemas.emailDefaultValues,
    schema: schemas.emailSchema,
  },
  {
    id: uuidv4(),
    icon: icons.fieldDate,
    label: "Date",
    fieldType: FormBuilderFieldTypes.DATE,
    defaultValues: schemas.dateDefaultValues,
    schema: schemas.dateSchema,
  },
  {
    id: uuidv4(),
    icon: icons.decisionBox,
    label: "Decision Box",
    fieldType: FormBuilderFieldTypes.DECISION_BOX,
    defaultValues: schemas.decisionBoxDefaultValues,
    schema: schemas.decisionBoxSchema,
  },
  {
    id: uuidv4(),
    icon: icons.dropDown,
    label: "Drop Down",
    fieldType: FormBuilderFieldTypes.DROPDOWN,
    defaultValues: createNonRecurringTaskDefaultValues,
    schema: CreateNonRecurringClientSchema(() => {}),
  },
  {
    id: uuidv4(),
    icon: icons.checkBox,
    label: "Check Box",
    fieldType: FormBuilderFieldTypes.CHECKBOX,
    defaultValues: schemas.checkboxDefaultValues,
    schema: schemas.checkboxSchema,
  },
  {
    id: uuidv4(),
    icon: icons.checkBox,
    label: "Radio",
    fieldType: FormBuilderFieldTypes.RADIO,
    defaultValues: schemas.radioBoxDefaultValues,
    schema: schemas.radioBoxSchema,
  },
  {
    id: uuidv4(),
    icon: icons.currency,
    label: "Currency",
    fieldType: FormBuilderFieldTypes.CURRENCY,
    defaultValues: schemas.currencyDefaultValues,
    schema: schemas.currencySchema,
  },
  {
    id: uuidv4(),
    icon: icons.fileUpload,
    label: "File Upload",
    fieldType: FormBuilderFieldTypes.FILE_UPLOAD,
    defaultValues: schemas.fileUploadDefaultValues,
    schema: schemas.fileUploadSchema,
  },
  {
    id: uuidv4(),
    icon: icons.imageUpload,
    label: "Image Upload",
    fieldType: FormBuilderFieldTypes.IMAGE_UPLOAD,
    defaultValues: schemas.imageUploadDefaultValues,
    schema: schemas.imageUploadSchema,
  },
  {
    id: uuidv4(),
    icon: icons.termsAndConditions,
    label: "Terms & Conditions",
    fieldType: FormBuilderFieldTypes.TERMS_AND_CONDITIONS,
    defaultValues: schemas.termsAndConditionsDefaultValues,
    schema: schemas.termsAndConditionsSchema,
  },
];

export default availableFields;
