version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
