export const initialState = {
  name: "",
  category: null,
  subCategory: null,
  client: [],
  frequency: null,
  feeAmount: null,
  priority: null,
  startDate: null,
  dueDate: null,
  members: [],
  labels: [],
  taskLeader: null,
  financialYear: null,
  expectedCompletionDate: null,
};

export const RecurringInitialState = {
  name: "",
  category: null,
  subCategory: null,
  client: [],
  frequency: null,
  feeAmount: null,
  priority: null,
  recurringStartDate: null,
  recurringEndDate: null,
  dueDay: null,
  customDates: [],
  members: [],
  labels: [],
  taskLeader: null,
  financialYear: null,
};
