export const initialState = {
  name: "",
  category: null,
  subCategory: null,
  client: null,
  recurring: false,
  frequency: null,
  feeAmount: null,
  priority: null,
  dueDate: null,
  recurringStartDate: null,
  recurringEndDate: null,
  dueDay: null,
  customDates: [],
  members: [],
  labels: [],
  taskLeader: null,
  taskType: null,
};
