export const initialState = {
  name: "",
  category: null,
  subCategory: null,
  labels: [],
  client: null,
  recurring: false,
  frequency: null,
  feeAmount: null,
  priority: null,
  startDate: null,
  dueDate: null,
  startDay: null,
  dueDay: null,
  endDate: null,
  members: [],
  taskLeader: null,
  taskType: null,
};
